export const ONE_MINUTE_IN_MILLISECONDS = 60000;

export const OTP_AGE_IN_MILLISECONDS = 5 * ONE_MINUTE_IN_MILLISECONDS;
export const RESET_TOKEN_AGE_IN_MILLISECONDS = 60 * ONE_MINUTE_IN_MILLISECONDS;
